### ISSUE TITLE
Ошибка новой версии

### ISSUE THREAD

**Issue by dtcmumuuser** [yegorov-p/python-zapret-info#2]
Здравствуйте!
Пользовался Вашим замечательным продуктом первой версии. Всё прекрасно работало. Обновил до новой, выходит ошибка
Traceback (most recent call last):
  File "zapret_checker.py", line 18, in <module>
    dt = datetime.strptime(ElementTree().parse("dump.xml").attrib['updateTime'][:19],'%Y-%m-%dT%H:%M:%S')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'dump.xml'
Подскажите, пожалуйста, в чем может быть дело.

**Comment by CBEPX** [comment]
очевидно в том что в том месте где ищет программа отсуствует файл dump.xml
 IOError: [Errno 2] No such file or directory: 'dump.xml'
Как вариант можете попробовать положить этот файл рядом и посмотреть что напишет после следующего запуска.

**Comment by yegorov-p** [comment]
Это же просто набросанный на коленке пример, описывающий работу с модулем, в котором реализована работа с API реестра. CBEPX совершенно прав, программе требуется положить dump.xml рядом со скриптом. Ну либо дописать две строчки в сам скрип, чтобы он корректно работал и "с нуля"

**Comment by dtcmumuuser** [comment]
Спасибо за быстрый ответ!
Вы оказались правы, пути недоисправил. Еще раз спасибо за отличный продукт!
