### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by sergeymarukhno** [yegorov-p/python-zapret-info#8]
Здравствуйте.
При запуске скрипта у меня выдаёт ошибку, подскажите в чем может быть проблема?
 python zapret_checker.py -r zapros.xml -s zapros.xml.sig
Traceback (most recent call last):
  File "zapret_checker.py", line 190, in <module>
    main()
  File "zapret_checker.py", line 52, in main
    session = ZapretInfo()
  File "/root/rkn_soc/zapretinfo.py", line 20, in __init__
    self.cl = suds.client.Client(API_URL)
AttributeError: 'module' object has no attribute 'client'

**Comment by yegorov-p** [comment]
Добрый день! Рискну предположить, что у вас какая-нибудь неканоничная версия suds стоит, но мне весьма сложно подебажить, так как у меня и файликов подписанных-то давно уже нет.

**Comment by sergeymarukhno** [comment]
Видать так оно и есть. Надругом сервере выполнился скрипт. Хорошо, спасибо, буду разбираться с версиями suds
